-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN     "internalNotes" JSONB,
ADD COLUMN     "tags" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "EmailPreset" ADD COLUMN     "forgotPasswordEmailBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "forgotPasswordEmailSubject" TEXT NOT NULL DEFAULT 'Reset Password',
ADD COLUMN     "orderCancelledBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "orderCancelledSubject" TEXT NOT NULL DEFAULT 'Order Cancelled',
ADD COLUMN     "orderConfirmationBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "orderConfirmationSubject" TEXT NOT NULL DEFAULT 'Order Confirmed',
ADD COLUMN     "orderReturnedBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "orderReturnedSubject" TEXT NOT NULL DEFAULT 'Order Returned',
ADD COLUMN     "paymentReceivedBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "paymentReceivedSubject" TEXT NOT NULL DEFAULT 'Payment Received',
ADD COLUMN     "paymentRejectedBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "paymentRejectedSubject" TEXT NOT NULL DEFAULT 'Payment Rejected',
ADD COLUMN     "shippingUpdateBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "shippingUpdateSubject" TEXT NOT NULL DEFAULT 'Shipping Update',
ADD COLUMN     "subscriptionActivatedBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "subscriptionActivatedSubject" TEXT NOT NULL DEFAULT 'Subscription Active',
ADD COLUMN     "trialExpiredBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "trialExpiredSubject" TEXT NOT NULL DEFAULT 'Trial Expired',
ADD COLUMN     "trialExpiryBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "trialExpirySubject" TEXT NOT NULL DEFAULT 'Trial Expiring',
ADD COLUMN     "verifyEmailBody" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "verifyEmailSubject" TEXT NOT NULL DEFAULT 'Verify Email',
ALTER COLUMN "welcomeEmailSubject" SET DEFAULT 'Welcome!',
ALTER COLUMN "welcomeEmailBody" SET DEFAULT '',
ALTER COLUMN "newOrderEmailSubject" SET DEFAULT 'New Order',
ALTER COLUMN "newOrderEmailBody" SET DEFAULT '',
ALTER COLUMN "lowStockEmailSubject" SET DEFAULT 'Low Stock',
ALTER COLUMN "lowStockEmailBody" SET DEFAULT '',
ALTER COLUMN "adminAlertEmailSubject" SET DEFAULT 'System Alert',
ALTER COLUMN "adminAlertEmailBody" SET DEFAULT '';

-- AlterTable
ALTER TABLE "SystemConfig" ADD COLUMN     "forgotPasswordEmailBody" TEXT,
ADD COLUMN     "forgotPasswordEmailSubject" TEXT NOT NULL DEFAULT 'Reset your ShopSync password',
ADD COLUMN     "orderCancelledBody" TEXT,
ADD COLUMN     "orderCancelledSubject" TEXT NOT NULL DEFAULT 'Order Cancelled ≡ƒÜ½',
ADD COLUMN     "orderConfirmationBody" TEXT,
ADD COLUMN     "orderConfirmationSubject" TEXT NOT NULL DEFAULT 'Order Confirmed! Γ£à',
ADD COLUMN     "orderReturnedBody" TEXT,
ADD COLUMN     "orderReturnedSubject" TEXT NOT NULL DEFAULT 'Return Received ≡ƒôª',
ADD COLUMN     "paymentReceivedBody" TEXT,
ADD COLUMN     "paymentReceivedSubject" TEXT NOT NULL DEFAULT 'Payment Proof Received ≡ƒôÑ',
ADD COLUMN     "paymentRejectedBody" TEXT,
ADD COLUMN     "paymentRejectedSubject" TEXT NOT NULL DEFAULT 'Payment Verification Failed Γ¥î',
ADD COLUMN     "shippingUpdateBody" TEXT,
ADD COLUMN     "shippingUpdateSubject" TEXT NOT NULL DEFAULT 'Your Package is on the Way! ≡ƒÜÜ',
ADD COLUMN     "subscriptionActivatedBody" TEXT,
ADD COLUMN     "subscriptionActivatedSubject" TEXT NOT NULL DEFAULT 'Subscription Activated! Γ£¿',
ADD COLUMN     "trialExpiredBody" TEXT,
ADD COLUMN     "trialExpiredSubject" TEXT NOT NULL DEFAULT 'Trial Expired ≡ƒöÆ',
ADD COLUMN     "trialExpiryBody" TEXT,
ADD COLUMN     "trialExpirySubject" TEXT NOT NULL DEFAULT 'Trial Ending Soon! ΓÅ│',
ADD COLUMN     "verifyEmailBody" TEXT,
ADD COLUMN     "verifyEmailSubject" TEXT NOT NULL DEFAULT 'Verify your ShopSync account';

