import {
  Injectable,
  Logger,
  BadRequestException,
  InternalServerErrorException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import axios, { AxiosInstance } from 'axios';

// ─── Public types ──────────────────────────────────────────────────────────────

export interface RedxArea {
  id: number;
  name: string;
  post_code: string;
}

export interface RedxCreateParcelPayload {
  /** Full name of the recipient */
  customer_name: string;
  /** BD mobile number, e.g. "01XXXXXXXXX" */
  customer_phone: string;
  /** Human-readable delivery area name, must match RedX catalogue */
  delivery_area: string;
  /** Numeric ID from GET /areas */
  delivery_area_id: number;
  /** Full street address of the recipient */
  customer_address: string;
  /** Unique invoice reference generated by ShopSync */
  merchant_invoice_id: string;
  /** Cash-on-delivery amount in BDT */
  cash_collection_amount: number;
  /** Parcel weight in grams (min 500) */
  parcel_weight: number;
  /** Declared value of goods in BDT */
  value: number;
}

export interface RedxParcelResult {
  trackingId: string;
  consignmentId: string;
}

// ─── Service ───────────────────────────────────────────────────────────────────

@Injectable()
export class RedxService {
  private readonly logger = new Logger(RedxService.name);

  /** Environment-driven base URL so we can toggle sandbox ↔ production. */
  private readonly baseUrl: string;

  constructor(private readonly configService: ConfigService) {
    this.baseUrl =
      this.configService.get<string>('REDX_BASE_URL') ||
      'https://sandbox.recbc.com.bd/v1.0.0-beta';
  }

  // ─── Private: build per-shop axios client ─────────────────────────────────

  private buildClient(token: string): AxiosInstance {
    return axios.create({
      baseURL: this.baseUrl,
      headers: {
        // RedX official auth header format
        'API-ACCESS-TOKEN': `Bearer ${token}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      timeout: 15_000,
    });
  }

  // ─── Public: fetch delivery areas ────────────────────────────────────────

  /**
   * Fetches the list of delivery areas from RedX.
   * Used to power the area autocomplete dropdown in the Order Slideover.
   *
   * @param token  Shop's RedX bearer token
   */
  async getAreas(token: string): Promise<RedxArea[]> {
    this.logger.log('Fetching RedX delivery areas');
    const client = this.buildClient(token);

    try {
      const { data } = await client.get<{ areas: RedxArea[] }>('/areas');
      this.logger.log(`Fetched ${data?.areas?.length ?? 0} RedX areas`);
      return data?.areas ?? [];
    } catch (err: any) {
      this.logger.error(
        `RedX GET /areas failed: ${err?.response?.data ? JSON.stringify(err.response.data) : err.message}`,
      );

      // Fallback: return a minimal mock so the UI stays functional during dev
      if (!this.configService.get('REDX_BASE_URL')) {
        this.logger.warn('REDX_BASE_URL not set – returning mock area list');
        return [
          { id: 1, name: 'Dhaka', post_code: '1200' },
          { id: 2, name: 'Chittagong', post_code: '4000' },
          { id: 3, name: 'Sylhet', post_code: '3100' },
          { id: 4, name: 'Rajshahi', post_code: '6000' },
          { id: 5, name: 'Khulna', post_code: '9100' },
        ];
      }

      throw new InternalServerErrorException(
        'Could not fetch delivery areas from RedX. Check your token.',
      );
    }
  }

  // ─── Public: create parcel ────────────────────────────────────────────────

  /**
   * Creates a parcel on the RedX platform for an order.
   * On success returns the RedX tracking_id (and consignment_id).
   *
   * @param payload  Validated parcel data
   * @param token    Shop's RedX bearer token
   */
  async createParcel(
    payload: RedxCreateParcelPayload,
    token: string,
  ): Promise<RedxParcelResult> {
    this.logger.log(
      `Creating RedX parcel for invoice ${payload.merchant_invoice_id}`,
    );

    this.validatePayload(payload);

    const client = this.buildClient(token);

    try {
      const { data } = await client.post<{
        tracking_id: string;
        consignment_id?: string;
        [key: string]: any;
      }>('/parcel', payload);

      if (!data?.tracking_id) {
        this.logger.error(
          `RedX returned success but no tracking_id: ${JSON.stringify(data)}`,
        );
        throw new InternalServerErrorException(
          'RedX did not return a tracking ID. Verify your API credentials.',
        );
      }

      this.logger.log(
        `RedX parcel created. tracking_id=${data.tracking_id}`,
      );

      return {
        trackingId: String(data.tracking_id),
        consignmentId: String(data.consignment_id ?? data.tracking_id),
      };
    } catch (err: any) {
      // Re-throw NestJS HTTP exceptions as-is
      if (err?.status) throw err;

      const redxMsg = err?.response?.data?.message ?? err?.message;
      this.logger.error(`RedX POST /parcel failed: ${redxMsg}`);

      // ------------------------------------------------------------------
      // DEVELOPMENT FALLBACK: simulate a successful RedX response when the
      // sandbox URL is unreachable or REDX_BASE_URL is not configured.
      // ------------------------------------------------------------------
      if (!this.configService.get('REDX_BASE_URL')) {
        this.logger.warn('REDX_BASE_URL not set – returning mock tracking ID');
        const mockId = `REDX-${Math.floor(Math.random() * 900_000 + 100_000)}`;
        return { trackingId: mockId, consignmentId: mockId };
      }

      throw new InternalServerErrorException(
        `RedX API error: ${redxMsg ?? 'Unknown error'}. Check your token and payload.`,
      );
    }
  }

  // ─── Private helpers ──────────────────────────────────────────────────────

  private validatePayload(payload: RedxCreateParcelPayload): void {
    if (!payload.customer_name?.trim()) {
      throw new BadRequestException('customer_name is required for RedX.');
    }
    if (!payload.customer_phone?.trim()) {
      throw new BadRequestException('customer_phone is required for RedX.');
    }
    if (!payload.delivery_area_id) {
      throw new BadRequestException(
        'delivery_area_id is required. Select a RedX delivery area first.',
      );
    }
    if (!payload.merchant_invoice_id?.trim()) {
      throw new BadRequestException('merchant_invoice_id is required for RedX.');
    }
    if (payload.parcel_weight < 500) {
      throw new BadRequestException(
        'parcel_weight must be at least 500 grams per RedX requirements.',
      );
    }
  }
}
